from default_settings import *

ZOHO_APPLICATION_LINK_NAME = "..."
ZOHO_PROFILE_VIEW_NAME = "..."
ZOHO_PROFILE_FORM_NAME = "..."
ZOHO_FACILITIES_VIEW_NAME = "..."
ZOHO_FACILITIES_FORM_NAME = "..."
ZOHO_AUTHENTICATION_TOKEN = "..."
ZOHO_OWNER_NAME = "..."
