# Generated by Django 2.2.12 on 2020-04-18 16:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blackandpink", "0016_memberprofile_zoho_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcheck",
            name="entry_after",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="contactcheck",
            name="entry_before",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="contactcheck",
            name="search_result",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="unknownfacilitymatch",
            name="breakdown",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name="updaterun",
            name="errors",
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
